[package]
name = "process_arch"
version = "0.1.0"
edition = "2021"
path = "src/main"

[dependencies]
libc = "0.2.12"
bincode = "1.3"
clap = { version = "4.3.23", features = ["derive"] }
os_pipe = "1.1.4"
command-fds = "0.2.2"


